name: Deploy (client) Frontend

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install Project Dependencies
      run: npm install
      working-directory: ./client 

    - name: Build React Application
      run: npm run build
      working-directory: ./client

    - name: Deploy Build Artifacts to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: pernixlocker 
        publish-profile: ${{ secrets.AZURE_PERNIXUI_PUBLISH_PROFILE }} 
        package: './client/build'
