name: Deploy (server) Backend

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Fetch only the latest commit

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install
      working-directory: ./server  

    # - name: Run tests
    #   run: npm test
    #   working-directory: ./server  

    - name: Set Environment Variables
      run: |
        echo "REACT_APP_API_SERVER=${{ secrets.REACT_APP_API_SERVER }}" >> $GITHUB_ENV
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
        echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
        echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> $GITHUB_ENV
        echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
        echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> $GITHUB_ENV

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'api-pernix-locker'  
        slot-name: 'Production'  # Deployment slot (use 'Production' for the main slot)
        package: './server'  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
