name: Deploy - pernix-api-locker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Install client dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Zip artifact for deployment
        run: |
          # Zip the server directory
          cd server
          zip -r ../server.zip .  # Zip the server files into server.zip in the root directory

          # Zip the client build directory
          cd ../client/build
          zip -r ../../client-build.zip .  # Zip the client build files into client-build.zip in the root directory

      - name: List files for debugging
        run: ls -R  # List all files in the root directory to verify the presence of server.zip and client-build.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            server.zip
            client-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files for debugging
        run: ls -R  # List all files in the root directory to verify downloaded files

      - name: Unzip server artifact
        run: unzip -d server server.zip  # Unzip server files into the server directory

      - name: Unzip client build artifact
        run: unzip -d client/build client-build.zip  # Unzip client build files into the client/build directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FD6EDD5C1F6B49989FF2EE749392A909 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE267B1AE40E4066A64B5C53B9DD5D3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_224E4995592B4998B113147275A5A529 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pernix-api-locker'
          slot-name: 'Production'
          package: ./server  # Adjust if necessary
