name: Deploy - pernix-api-locker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run tests in server
        run: |
          cd server
          npm test

      - name: Install client dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r release.zip .
          cd ../client/build
          zip -r ../../server/client-build.zip .

      - name: List files for debugging
        run: |
          ls -R server
          ls -R client/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            server/release.zip
            server/client-build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files for debugging
        run: ls -R

      - name: Create directory for client build
        run: mkdir -p client/build

      - name: Unzip server artifact
        run: unzip -d server release.zip

      - name: Unzip client build artifact
        run: unzip -d client/build client-build.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pernix-api-locker'
          slot-name: 'Production'
          package: ./server
